### ISSUE TITLE
作者您好，添加解析短视频封面的功能在技术上是否能够实现？

### ISSUE THREAD

**Issue by b921603** [jw-star/DouYintg_bot#2]
作者您好，添加解析短视频封面的功能在技术上是否能够实现？

**Comment by jw-star** [comment]
部分视频获取不到封面，只能截取视频的第一帧

**Comment by jw-star** [comment]
我修复下吧

**Comment by b921603** [comment]
感谢！目前bot支持添加群组吗？

**Comment by b921603** [comment]
询问一下，请问目前解析视频封面已经加入到bot功能里了吗？

**Comment by jw-star** [comment]
没呢，最近忙，周末吧

**Comment by jw-star** [comment]
> 感谢！目前bot支持添加群组吗？

群组 /dl 加链接

**Comment by b921603** [comment]
目前沒法把bot加到群組
![Screenshot_20230319-160744259](https://user-images.githubusercontent.com/18284133/226162109-3690b4c5-0836-4c20-9031-d349f075c6f1.jpg)

**Comment by jw-star** [comment]
> 目前沒法把bot加到群組 ![Screenshot_20230319-160744259](https://user-images.githubusercontent.com/18284133/226162109-3690b4c5-0836-4c20-9031-d349f075c6f1.jpg)

已给机器人权限，再试下
